CREATE SCHEMA `QuanLyBoardGame` ;
USE QuanLyBoardGame;


-- tao bang
CREATE TABLE BOARDGAME
(
	MASP VARCHAR(100) PRIMARY KEY,
	TENSP VARCHAR(100) ,
	GIA int ,
	THELOAI VARCHAR(100),
	SOLUONG int,
	MOTA TEXT
);

CREATE TABLE CUSTOMERS
(

	USERNAME VARCHAR(100) PRIMARY KEY,	
	HOTEN VARCHAR(100) NOT NULL ,
	`PassWord` VARCHAR(255) NOT NULL ,
	sdt varchar(12) not null,
    email varchar(100) not null

);

CREATE TABLE ADMINS
(
	ID  INT AUTO_INCREMENT PRIMARY KEY,
	UserName VARCHAR(100) ,	
	HOTEN VARCHAR(100) NOT NULL ,
	`PassWord` VARCHAR(255) NOT NULL,
    sdt varchar(12) not null,
    email varchar(100) not null
);

CREATE TABLE THUE
(
    ID_THUE VARCHAR(100) PRIMARY KEY,
    USERNAME VARCHAR(100),
    NGAYTHUE DATE,
    NGAYTRA DATE,
    TONGTIEN INT,
    FOREIGN KEY (USERNAME) REFERENCES Customers(USERNAME)
);
CREATE TABLE THUEGAME
(
	ID_THUE VARCHAR(100)  ,
    MASP VARCHAR(100),
    SOLUONG INT,
    PRIMARY KEY(ID_THUE,MASP),
    FOREIGN KEY (ID_THUE) REFERENCES THUE(ID_THUE),
    FOREIGN KEY (MASP) REFERENCES BOARDGAME(MASP)
);

CREATE TABLE LS_NAP
(
	ID INT PRIMARY KEY,
	USERNAME VARCHAR(100),
    SOTIEN INT,
    NGAYNAP DATE,
	FOREIGN KEY (USERNAME) REFERENCES CUSTOMERS(USERNAME)
);
CREATE TABLE TRAGAME
(
	ID_TRA VARCHAR(100) ,
    ID_THUE VARCHAR(100) ,
    NGAYTRA DATE,
    PRIMARY KEY(ID_TRA,ID_THUE),
    FOREIGN KEY (ID_THUE) REFERENCES THUE(ID_THUE)
);
INSERT INTO ADMINS(USERNAME,HOTEN,`PASSWORD`,SDT,EMAIL) VALUES('21522106','Hoàng Ngọc Hồng','hong1234','0366928921','hoangngochong03@gmail.com'),
('21522159','Nguyễn Thành Huy','huy1234','0','thanhhuy'),
('21522592','Nguyễn Trần Hội Thắng','thang1234','0','thang'),
('21522106','Từ Thì Huệ','hue1234','0','hue');

INSERT INTO CUSTOMERS(USERNAME,HOTEN,`PASSWORD`,SDT,EMAIL) VALUES('toannguyen','Nguyễn Văn Toàn','toan1111','0123456789','toan321@gmail.com'),
('vantran','Trần Thụy Vân','van360','0123456789','vantran103@gmail.com');
-- INSERT INTO BOARDGAME(MASP,TENSP,GIA,THELOAI,SOLUONG,MOTA) VALUES();

